image: registry.gitlab.com/midincihuy/laravel-test-deploy:latest

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - test
  - deploy

unit_test:
  stage: test
  script:
    - composer update

deploy_production:
  stage: deploy
  script:
    - echo "deploying"
  environment:
    name: production
    url: http://35.240.200.94
  only:
    - master