image: registry.gitlab.com/midincihuy/laravel-test-deploy:latest

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  DB_USERNAME: root

stages:
  - test
  - deploy

unit_test:
  stage: test
  script:
    - echo "Start testing"
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:fresh --seed

deploy_production:
  stage: deploy
  script:
    - echo "deploying"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SPK_GCL")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo $SPK_GCL
    - echo ~/.ssh/config
    - echo ~/.ssh/id_rsa
    - ~/.composer/vendor/bin/envoy run deploy
    - 'which mysql || ( apt-get update -y && apt-get install mysql-client -y )'
    - /usr/bin/mysql -uroot -e "show databases;"
  environment:
    name: production
    url: http://35.240.200.94
  when: manual
  only:
    - master